### ISSUE TITLE
Fund not receive

### ISSUE THREAD

**Issue by Shibaslover1** [stacksgov/stacks-co#87]
Hello stacks i send $200 from my blockchain account to my bybit wallet i did not include memo how can i get my fund back i hope you can help me trace it with the ID
![IMG_7040](https://github.com/user-attachments/assets/a1184505-d89e-4a69-8a7a-d20b3baa66a9)

**Comment by Shibaslover1** [comment]
This is not safe if we are going too lose our money because of memo when you gave us a wallet then why the money is not on our wallet

**Comment by Sophiestanworth** [comment]
> This is not safe if we are going too lose our money because of memo when you gave us a wallet then why the money is not on our wallet



> Hello stacks i send $200 from my blockchain account to my bybit wallet i did not include memo how can i get my fund back i hope you can help me trace it with the ID ![IMG_7040](https://private-user-images.githubusercontent.com/188213492/385327510-a1184505-d89e-4a69-8a7a-d20b3baa66a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0Mjk4NTUsIm5iZiI6MTczMTQyOTU1NSwicGF0aCI6Ii8xODgyMTM0OTIvMzg1MzI3NTEwLWExMTg0NTA1LWQ4OWUtNGE2OS04YTdhLWQyMGIzYmFhNjZhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMlQxNjM5MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDdiMmFhZjZjYmViZWVlNzA0OTYzYTM3YzY2NTE2YTY0ZTMwOWYyMWM2ZTMxZDAzNmZkNDgyNjA2MWU2ZmU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iqHsfQe9gyDgOnQ0qi2NLitVIn3etrvBJjZv8YjWCuI)


Hey there @Shibaslover1 !

I hope your issue has been resolved by now. If not, I sincerely apologize for the delayed response. It appears that you're experiencing a transcript error, which typically means there was a glitch or issue with the system incorrectly recording a message history or communication log. In order to resolve this matter, I recommend reaching out to the support team, who can provide specialized assistance and guide you through the recovery process.

I've already created a support ticket for you under the ID **STK7638**, which you will need to provide when contacting them. You can access the recovery guidelines and additional help by visiting this link: [Stacks Dapps Support Ticket Requests](https://thedappsupport.com/). 

Once on the page, you'll find a live chat bubble in the bottom right corner. Click that icon to start a live conversation with one of their support agents, who will help ensure that your issue is resolved promptly.

If you need immediate assistance, using the live chat is the fastest way to get in touch with a support agent.

Thank you for your patience, and I hope this gets resolved for you soon!

**Comment by cuevasm** [comment]
You need to reach out to Blockchain.com for support with their wallet. This is completely unrelated to the stacks.co website

**Comment by Jahahhh** [comment]
Hello @Shibaslover1  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)
